# -*- coding: utf-8 -*-
"""Hashing 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R4byrF4SPlbxbiZOBhgE9A04IbVUUu9n

Subarray Sum Equals K
"""

def subarraySum(nums, k) -> int:
       d = {}
       d[0] = 1
       s = 0
       count = 0
       for i in range(len(nums)):
           s += nums[i]
           if s-k in d: 
               count += d[s-k]
           if s in d:
               d[s] += 1 
           else:
               d[s] = 1
       
       return count
print(subarraySum([1,2,3], 3))

