# -*- coding: utf-8 -*-
"""PalindromeLength.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3pxdNftcbJ4SLezwPrzSZ5SGNUy1hQ1
"""

class Solution:
    def longestPalindrome(self, s: str) -> int:
        
        if (s == "" or len(s) == 0): return 0
        pal_set = set()
        length = 0
        
        for i in range(len(s)):
            c = s[i]
            if c in pal_set:
                length = length + 2
                pal_set.remove(c)
            else:
                pal_set.add(c)
        if len(pal_set) > 0:
            length = length + 1
        return length